### ISSUE TITLE
endless logon

### ISSUE THREAD

**Issue by MaplerStory** [DoctorMcKay/node-steam-user#357]
## Describe the bug
in some special scenes, the lib will cause an endless logon action.

the endless logon was caused by this code.
https://github.com/DoctorMcKay/node-steam-user/blob/967a031937f2f5be02ca0f068f5ce506a0d740c7/components/connection.js#L7-L19

if the steam cm client stream discounected the account logon, then it will cause those endless action;
even after call the logOff(), the _doConnection() will be called again and again.
https://github.com/DoctorMcKay/node-steam-user/blob/967a031937f2f5be02ca0f068f5ce506a0d740c7/components/connection.js#L14

## Versions
What version of the module and what version of Node.js are you using?
all version, include the latest version: v4.19.8

## Screenshots and Error Logs
If applicable, add screenshots and error logs to help explain your problem.

> Bot userxxxx do logOn.
[client debug]: account:userxxxx, [W2] Randomly chose WebSocket CM cm4-hkg1.cm.steampowered.com:27026
[client debug]: account:userxxxx, [W2] WebSocket connection success; now logging in
[client debug]: account:userxxxx, Sending message: ClientLogon
[client debug verbose]: userxxxx, [W2] Queueing frame 2, FIN, MASK, payload 267 bytes
[client debug verbose]: userxxxx, [W2] Got frame 2, FIN, payload 63 bytes
[client debug verbose]: userxxxx, === Processing multi msg W2#1 (49 bytes) ===
[client debug verbose]: userxxxx, [W2] Got frame 8, FIN, payload 2 bytes
[client debug verbose]: userxxxx, [W2] Sending frame 8, FIN, MASK, payload 2 bytes
[client debug]: account:userxxxx, [W2] WebSocket disconnected with code 1000 and reason:
[client debug]: account:userxxxx, [W2#1] Handled message: ClientLogOnResponse
[client debug]: account:userxxxx, Disconnecting without sending logoff
[client debug]: account:userxxxx, [W2] We wanted to end connection, but it's not connected or connecting
[client debug verbose]: userxxxx, === Finished processing multi msg W2#1; now clearing queue of size 0 ===
Bot userxxxx logOff.
[client debug]: account:userxxxx, Disconnecting
[client debug]: account:userxxxx, [W2] We wanted to end connection, but it's not connected or connecting
[client debug verbose]: userxxxx, [W2] Socket closed after successful websocket closure.
[client debug]: account:userxxxx, [W3] Randomly chose WebSocket CM cm3-hkg1.cm.steampowered.com:27020
[client debug]: account:userxxxx, [W3] WebSocket connection success; now logging in
[client debug]: account:userxxxx, Dropping message 5514 because we're not logged on.
[client debug]: account:userxxxx, Logon message timeout elapsed. Attempting relog.
[client debug]: account:userxxxx, Disconnecting without sending logoff
[client debug]: account:userxxxx, [W3] Ending connection and removing all listeners
[client debug]: account:userxxxx, [W4] Randomly chose WebSocket CM cm3-hkg1.cm.steampowered.com:27020
[client debug]: account:userxxxx, [W4] WebSocket connection success; now logging in
[client debug]: account:userxxxx, Sending message: ClientLogon
[client debug verbose]: userxxxx, [W4] Queueing frame 2, FIN, MASK, payload 267 bytes
[client debug verbose]: userxxxx, [W4] Got frame 2, FIN, payload 63 bytes
[client debug verbose]: userxxxx, === Processing multi msg W4#2 (49 bytes) ===
[client debug verbose]: userxxxx, [W4] Got frame 8, FIN, payload 2 bytes
[client debug verbose]: userxxxx, [W4] Sending frame 8, FIN, MASK, payload 2 bytes
[client debug]: account:userxxxx, [W4] WebSocket disconnected with code 1000 and reason:
[client debug]: account:userxxxx, [W4#2] Handled message: ClientLogOnResponse
[client debug]: account:userxxxx, Disconnecting without sending logoff
[client debug]: account:userxxxx, [W4] We wanted to end connection, but it's not connected or connecting
[client debug verbose]: userxxxx, === Finished processing multi msg W4#2; now clearing queue of size 0 ===
[client debug verbose]: userxxxx, [W4] Socket closed after successful websocket closure.
[client debug]: account:userxxxx, [W5] Randomly chose WebSocket CM cm3-hkg1.cm.steampowered.com:443
[client debug]: account:userxxxx, [W5] WebSocket connection success; now logging in
[client debug]: account:userxxxx, Dropping message 5514 because we're not logged on.
[client debug]: account:userxxxx, Logon message timeout elapsed. Attempting relog.
[client debug]: account:userxxxx, Disconnecting without sending logoff
[client debug]: account:userxxxx, [W5] Ending connection and removing all listeners
[client debug]: account:userxxxx, [W6] Randomly chose WebSocket CM cm2-hkg1.cm.steampowered.com:27020
[client debug]: account:userxxxx, [W6] WebSocket connection success; now logging in
[client debug]: account:userxxxx, Sending message: ClientLogon
[client debug verbose]: userxxxx, [W6] Queueing frame 2, FIN, MASK, payload 267 bytes
[client debug verbose]: userxxxx, [W6] Got frame 2, FIN, payload 63 bytes
[client debug verbose]: userxxxx, === Processing multi msg W6#3 (49 bytes) ===
[client debug verbose]: userxxxx, [W6] Got frame 8, FIN, payload 2 bytes
[client debug verbose]: userxxxx, [W6] Sending frame 8, FIN, MASK, payload 2 bytes
[client debug]: account:userxxxx, [W6] WebSocket disconnected with code 1000 and reason:
[client debug]: account:userxxxx, [W6#3] Handled message: ClientLogOnResponse
[client debug]: account:userxxxx, Disconnecting without sending logoff

this is the log for that endless logon action

**Comment by DoctorMcKay** [comment]
That looks like Steam is down, so the reconnection attempts are normal.

**Comment by DoctorMcKay** [comment]
If this isn't a result of a Steam outage, 4.19.9 should fix it.

**Comment by ndrrsn** [comment]
Hey there! 4.19.9 does not fix it for me, I'm getting endless logon with basic bot [example](https://github.com/DoctorMcKay/node-steam-user/blob/master/examples/basicbot.js), in the same time i can login in Steam itself using the same account.

**Comment by DoctorMcKay** [comment]
It looks like Steam isn't sending back a ClientLogOnResponse for some reason. Can you please also include output from the `debug-verbose` event?
