### ISSUE TITLE
Call to non-existing function this.debug after steam-session failure

### ISSUE THREAD

**Issue by metzz1** [DoctorMcKay/node-steam-user#456]
Seems like after todays update (12/09/2023) something broke on the package, seems to be related to Polling, havent really investigated as of now.

Heres the output of the error:
`this.debug is not a function`

After commenting the debug function (which seems like it does not exist on file) we get: 
`Error: FileNotFound`

Best Regards,

**Comment by endze1t** [comment]
I'm experiencing the same issue. It appears to be related to the [node-steam-session](https://github.com/DoctorMcKay/node-steam-session) package, and it seems that Steam may have removed a previously used endpoint, `PollAuthSessionStatus`.

**Comment by web3yc** [comment]
same issue,fix pls ASAP

**Comment by sap2me** [comment]
> I'm experiencing the same issue. It appears to be related to the [node-steam-session](https://github.com/DoctorMcKay/node-steam-session) package, and it seems that Steam may have removed a previously used endpoint, `PollAuthSessionStatus`.

and this endpoint return eresult: 9 that meens "FileNotFound" regardless any params

**Comment by web3yc** [comment]
> 
can post it on his forum

**Comment by Moder112** [comment]
It seems like the newest unaffected version is 4.27.1.
Downgrading from 4.29.1 resolved the issues in my production environment at least on the surface level.
Haven't tested whether everything works, but at least stuff like confirming and accepting trades seems to.

**Comment by web3yc** [comment]
> 

thank bro, I successfully logged in through downgrade and confirmed the offer

**Comment by web3yc** [comment]
> 最新的不受影响的版本似乎是 4.27.1。 从 4.29.1 降级至少在表面上解决了我的生产环境中的问题。 还没有测试一切是否有效，但至少确认和接受交易之类的东西似乎有效。
thank bro, I successfully logged in through downgrade and confirmed the offer

**Comment by web3yc** [comment]
> It seems like the newest unaffected version is 4.27.1. Downgrading from 4.29.1 resolved the issues in my production environment at least on the surface level. Haven't tested whether everything works, but at least stuff like confirming and accepting trades seems to.

thank bro, I successfully logged in through downgrade and confirmed the offer

**Comment by hybran** [comment]
Seems when you replace the this.debug with a console.log, I get "FileNotFound" error, but as mentioned above downgrading to  4.27.1 solves it!

**Comment by DoctorMcKay** [comment]
The call to `this.debug` is a separate issue. The login failure issue is here: https://github.com/DoctorMcKay/node-steam-session/issues/27

**Comment by moobyes** [comment]
The steam-session has updated!

**Comment by DoctorMcKay** [comment]
The wrong debug function call is fixed in [steam-user 4.29.2](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.29.2), and the Steam login problem is fixed in [steam-session 1.3.1](https://github.com/DoctorMcKay/node-steam-session/releases/tag/v1.3.1).

**Comment by thouravi** [comment]
I am still getting the same error despite updating the package.

```
TypeError: this.debug is not a function
at LoginSession. (/home/ubuntu/scripts/appInfo/node_modules/steam-user/components/09-logon.js:366:10)
at LoginSession.emit (node:events:513:28)
at LoginSession._doPoll (/home/ubuntu/scripts/appInfo/node_modules/steam-session/dist/LoginSession.js:483:22)
```
